
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INT OPR WORDexp : termexp : exp termterm : factterm : term factfact : INTfact : WORDfact : OPR'
    
_lr_action_items = {'INT':([0,1,2,3,4,5,6,7,8,],[4,4,4,-3,-5,-6,-7,4,-4,]),'WORD':([0,1,2,3,4,5,6,7,8,],[5,5,5,-3,-5,-6,-7,5,-4,]),'OPR':([0,1,2,3,4,5,6,7,8,],[6,6,6,-3,-5,-6,-7,6,-4,]),'$end':([1,2,3,4,5,6,7,8,],[0,-1,-3,-5,-6,-7,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,],[1,]),'term':([0,1,],[2,7,]),'fact':([0,1,2,7,],[3,3,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> term','exp',1,'p_exp1','expression_gt.py',7),
  ('exp -> exp term','exp',2,'p_exp2','expression_gt.py',11),
  ('term -> fact','term',1,'p_term1','expression_gt.py',28),
  ('term -> term fact','term',2,'p_term3','expression_gt.py',32),
  ('fact -> INT','fact',1,'p_factInt','expression_gt.py',43),
  ('fact -> WORD','fact',1,'p_factWord','expression_gt.py',48),
  ('fact -> OPR','fact',1,'p_factOPR','expression_gt.py',54),
]
